site_name: HPC Wiki
site_description: HPC Wiki
site_author: HPC Wiki Team
site_url: https://hpcwiki.io/
repo_name: lcpu-club/hpc-wiki
repo_url: https://github.com/lcpu-club/hpc-wiki
edit_uri: blob/master/docs/zh/docs/
copyright: Copyright &copy; 2023 - 2023 HPC Wiki Team
theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: static/img/logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- Start:
  - index.md
  - 贡献指南:
    - contribute/before-contributing.md
    - contribute/basic-contribute-approach.md
    - contribute/documentation-requirement.md
- HPC简介:
  - hpc-intro/what-is-hpc.md
  - hpc-intro/hpc-history.md
  - hpc-intro/modern-hpc.md
- HPC比赛简介:
  - competition/competition-intro.md
  - competition/sc.md
  - competition/isc.md
  - competition/asc.md
  - competition/hpcgame.md
  - competition/other.md
- 超算平台的使用:
  - platform/platform-intro.md
  - platform/cluster.md
  - platform/cloud.md
  - platform/scheduling.md
  - platform/modules.md
- 硬件:
  - hardware/hardware-intro.md
  - hardware/processor.md
  - hardware/memory.md
  - hardware/gpu-and-fpga.md
  - hardware/interconnect.md
  - hardware/storage.md
- 并行编程:
  - parallel-programming/parallel-programming-intro.md
  - parallel-programming/mpi.md
  - parallel-programming/openmp.md
  - parallel-programming/gpu.md
  - parallel-programming/nccl.md
  - parallel-programming/opencl.md
  - parallel-programming/openacc.md
  - parallel-programming/mpi4py.md
- 通信:
  - communication/intro.md
  - communication/model.md
  - communication/cost.md
  - communication/deadlock.md
- 性能分析:
  - performance-analysis/intro.md
  - performance-analysis/basics.md
  - performance-analysis/vtune.md
  - performance-analysis/nsys.md
- Benchmark:
  - benchmark/intro.md
  - benchmark/hpl.md
  - benchmark/hpcg.md
  - benchmark/mlperf.md
- 科学计算与机器学习系统:
  - sci-mlsys/intro.md
  - sci-mlsys/parallelism.md
  - sci-mlsys/sparsity.md
  - sci-mlsys/quantization.md
- 功耗管理:
  - power-management/intro.md
  - power-management/perception.md
- Misc:
  - misc/faq.md
  - misc/shell.md
  - misc/git.md
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra:
  alternate:
  - link: /
    name: zh - 汉语
  - link: /en/
    name: en - English
  copyright: CC BY-NC-SA 4.0
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
- static/css/extra.css
